package com.org.acpgimini.logopr;

public class Calling {
public static void main(String[] args) {
	int a=BasicArithmetic.add(5,8);
	System.out.println(a);
	System.out.println(BasicArithmetic.mul(34, 44));
}
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         